### ISSUE TITLE
[LINUX] Loose Cannon charge meter offset from shield charge meter

### ISSUE THREAD

**Issue by Duptier** [Malgreen/funkehud-reloaded#1]
Exhibit Number 1:
![Screenshot_20210912_111940](https://user-images.githubusercontent.com/82429716/132967532-b973d4a6-24f7-4242-b104-7b26801dd3c8.png)

Another Weird text issue with min-mode off:
![Screenshot_20210912_112104](https://user-images.githubusercontent.com/82429716/132967543-e80a50f2-85af-4b16-8e25-e7c6672b0251.png)

The only thing I have edited myself for this hud is the location of the hud player class model and adding main menu characters.

If it helps, (because I've seen on huds.tf that huds are operating system specific) I am currently using Arch Linux.

**Comment by Malgreen** [comment]
This also isn't happening on Windows, but if I ever start using Linux I'll look into it

**Comment by Duptier** [comment]
Are you still sure? I booted into my Windows 10 Installation a few days ago and found the issue still remains.
