### ISSUE TITLE
[LINUX] Sniper bow charge meters slightly larger than Jarate's charge meter, and also cuts slightly into health cross

### ISSUE THREAD

**Issue by Duptier** [Malgreen/funkehud-reloaded#2]
Exhibit Number 1:

![Screenshot_20210920_180839](https://user-images.githubusercontent.com/82429716/133972837-d95b9512-3704-4a69-851f-ccca4657d951.png)

Issue only occurs in HUD Min-mode. No issue in the counterpart.

**Comment by Malgreen** [comment]
This isn't happening on Windows, but if I ever start using Linux I'll look into it

**Comment by Duptier** [comment]
Weird, the HUD files available here show no issue.
It's possible the huds.tf page for this HUD is outdated, because I also see various differences between this version and the one I was using before (which I downloaded from huds.tf).
Anyway, since it's resolved, I'm gonna close both the issues now.

**Comment by Malgreen** [comment]
Yup, I updated the huds.tf file, my bad...
